name: Publish Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate gh
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Publish GitHub Release
        run: |
          ./release.sh <<EOF
          1
          EOF
