name: Publish Release

on:
  push:
    branches:
      - main

    paths:
      - ".*"
      - ".aws/*"
      - "release.sh"
      - ".github/workflows/release.yaml"

  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: env bash ./release.sh
